apiVersion: v1 
kind: ResourceQuota 
metadata: 
    name: group-resource-quota 
    namespace: bd-g08 
spec: 
    hard: 
      requests.cpu: "2"
      limits.cpu: "4" 
      requests.memory: 2Gi 
      limits.memory: 4Gi 
      requests.storage: 8Gi 
      persistentvolumeclaims: "2" 
      pods: "10" 
