apiVersion: v1
kind: Pod
metadata:
  name: quota-negative
  namespace: bd-g08
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: registry.k8s.io/pause:3.10
      resources:
        requests:
          cpu: "3"
          memory: 128Mi
        limits:
          cpu: "3"
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
