apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"name":"group-resource-quota","namespace":"bd-g08"},"spec":{"hard":{"limits.cpu":"4","limits.memory":"4Gi","persistentvolumeclaims":"2","pods":"10","requests.cpu":"2","requests.memory":"2Gi","requests.storage":"8Gi"}}}
  creationTimestamp: "2026-10-03T17:50:01Z"
  name: group-resource-quota
  namespace: bd-g08
  resourceVersion: "1791129599233631004"
  uid: 8a4317a2-19f2-482b-80a1-45759a69663a
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: 8Gi
status:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: 8Gi
  used:
    limits.cpu: 3600m
    limits.memory: 3840Mi
    persistentvolumeclaims: "1"
    pods: "8"
    requests.cpu: 1200m
    requests.memory: 1408Mi
    requests.storage: 4Gi
