apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"observer","namespace":"bd-g08"}}
  creationTimestamp: "2026-10-03T17:19:46Z"
  name: observer
  namespace: bd-g08
  resourceVersion: "1791047986408063016"
  uid: 26664080-1bbf-41b4-9247-e54ab2745f6c
